# Generated by Django 5.0.6 on 2024-06-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='estado',
            field=models.CharField(choices=[('EnStock', 'EnStock'), ('Agotado', 'Agotado')], default='Agotado', max_length=50),
        ),
        migrations.AddField(
            model_name='figura',
            name='imagen',
            field=models.ImageField(default='default_image.jpg', upload_to='nuevasfiguras'),
        ),
    ]
